# Generated by Django 5.2.8 on 2025-11-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manufacture_date', models.DateField()),
                ('transport_details', models.CharField(max_length=20)),
                ('product_quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
